version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coco
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_1:/var/lib/mysql

  server:
    build:
      context: ./sv_be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coco
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ./sv_fe/user
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db
      - server
  admin:
    build:
      context: ./sv_fe/admin
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - db
      - server
volumes:
  db_data_1:
